// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOr6wljOL9qeJBJnTJ2gY09xz62xfa6So',
    appId: '1:1040970406800:web:2bceeb681739349b3e7115',
    messagingSenderId: '1040970406800',
    projectId: 'washfamily-001',
    authDomain: 'washfamily-001.firebaseapp.com',
    storageBucket: 'washfamily-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdBlT_ElDcmSmbUQ5npvZL8dyuO3TgIE',
    appId: '1:1040970406800:android:65d417b6e77f15e43e7115',
    messagingSenderId: '1040970406800',
    projectId: 'washfamily-001',
    storageBucket: 'washfamily-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4sFGk0HxUwtmsZp4ANzVefdzVMSIUJpI',
    appId: '1:1040970406800:ios:11b6c5c299e05eb63e7115',
    messagingSenderId: '1040970406800',
    projectId: 'washfamily-001',
    storageBucket: 'washfamily-001.firebasestorage.app',
    iosBundleId: 'com.washfamily.washfamily',
  );
}
